runtime: python
env: flex


entrypoint: gunicorn -b :8080 app:app
#entrypoint: gunicorn -b :$PORT app:app
env_variables:
  CLOUD_SQL_CONNECTION_NAME: 'cs348groupproject:us-east1:cs348-wishlist-db'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'password348'
  MYSQL_DB: 'test'

# handlers:
# Matches requests to /images/... to files in static/images/...
#- url: /images
#  static_dir: static/images

#- url: /.*
#  secure: always
#  redirect_http_response_code: 301
#  script: auto

runtime_config:
  python_version: 3

beta_settings:
  cloud_sql_instances: "cs348groupproject:us-east1:cs348-wishlist-db"
