runtime: python
env: flex


entrypoint: gunicorn -b :8080 app:app
#entrypoint: gunicorn -b :$PORT app:app
env_variables:
  CLOUD_SQL_CONNECTION_NAME: 'cs348groupproject:us-east1:cs348-wishlist-db'
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'password348'
  MYSQL_DB: 'test'

#
runtime_config:
  python_version: 3

beta_settings:
  cloud_sql_instances: "cs348groupproject:us-east1:cs348-wishlist-db"
